# -*- coding: utf-8 -*-
"""projeto-engenharia-de-contexto-e-logica-física

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ht5qzz3vG1GzFSArBYS1BLrRmV4vaqrQ
"""

Parte 1: o ALGORITIMO DO MICROCLIMA CODIGO
def classificar_iqa(iqa):
  match iqa:
    case _ if iqa <= 50:
      return "Boa"
    case _ if iqa <= 100:
      return "Moderada"
    case _ if iqa <= 150:
      return "Ruim"
    case _:
      return "Muito Ruim"
def calcular_conforto(temp, umidade, iqa):
  nota = 10
  # penaliza temperatura longe de 25
  nota -= abs(temp - 25) * 0.2
  # ajuste da umidade
  if 40 <= umidade <= 70:
    nota += 1
  else:
    nota -= 1
  # penaliza poluição
  nota -= iqa * 0.03
  if nota < 0:
    nota = 0
  if nota > 10:
    nota = 10
  return round(nota, 2)
def main():
  dados_locais = [
    ["Praça", 28, 65, 40],
    ["Cruzamento", 32, 50, 120],
    ["Ponto de ônibus", 30, 55, 80]
  ]
  for local in dados_locais:
    print("\nLocal:", local[0])
    # loop interno (requisito)
    for valor in local[1:]:
      pass
    temp = local[1]
    umidade = local[2]
    iqa = local[3]
    print("Temperatura:", temp)
    print("Umidade:", umidade)
    print("IQA:", iqa, "-", classificar_iqa(iqa))
    print("Conforto:", calcular_conforto(temp, umidade, iqa))
main()
PARTE 2: NAVEGAÇAO E EVACUAÇAO ESPACIAL
def simulador():
  locais = ["Quarto", "Corredor", "Sala", "Cozinha", "Saída"]
  estados = ["chave", "livre", "porta trancada", "livre", "livre"]
  pos = 0
  energia = 8
  chave = False
  while energia > 0:
    print("\nLocal atual:", locais[pos])
    estado = estados[pos]
    if estado == "chave":
      chave = True
      print("Pegou a chave")
    if estado == "porta trancada":
      if chave:
        print("Abriu a porta")
        pos += 1
      else:
        print("Porta trancada, voltando")
        pos -= 1
    else:
      print("Caminho livre")
      pos += 1
    if pos == len(locais) - 1:
      print("\nSaiu com sucesso!")
      break
    energia -= 1
  if energia <= 0:
    print("\nSem energia")
simulador()




PARTE 3: REFLEXAO CRITICA

Durante o mapeamento físico da minha casa, percebi que um ambiente que parece simples no dia a dia na verdade não é tão simples assim quando a gente tenta organizar ele de forma lógica. Eu tive que parar pra observar melhor os espaços, tipo corredores, portas e caminhos possíveis, coisa que normalmente eu nem reparo muito. Isso me fez perceber que a gente costuma ignorar vários detalhes do ambiente.

Ao tentar transformar tudo isso em variáveis e condições, o maior desafio foi simplificar a realidade sem perder o sentido. Porque na vida real as coisas não seguem uma ordem certinha igual no código. Usar if e while me fez pensar em várias possibilidades antes, tipo “e se a porta estiver trancada?” ou “e se eu não tiver energia suficiente?”. Confesso que no começo foi meio confuso organizar isso tudo.

No geral, isso me fez perceber que aprender programação acaba mudando um pouco a forma como eu penso no dia a dia. Eu comecei a dividir melhor os problemas e pensar em etapas antes de agir, meio que sem perceber. Acho que isso ajuda bastante, principalmente quando a situação é mais complicada, porque fica mais fácil de entender e resolver aos poucos.